version: 1.0.0
name: prod
apps:
  - uuid: 3c967400-a486-11f0-b373-43a88aba43f2
    release: 1.1.0
  - uuid: 5d27b2be-a487-11f0-9f52-bb17db4e5ac8
    release: latest
  - uuid: 79ff5ec8-d6d2-11f0-b92d-a3ee240ab4a7
    release: latest
  - uuid: c0094bc4-a47b-11f0-8270-ab20c73baea0
    release: 1.1.0
  - uuid: d03bd10e-a482-11f0-927b-b37aaafa7e61
    release: latest
